=== shankar-trainer/hello-world/tibco-webservice-batch/xml/XmlProject/EmployeeDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/EmployeeDetails"
	xmlns:tns="http://www.example.org/EmployeeDetails"
	elementFormDefault="qualified">
	<xs:element name="EmployeeDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:integer"></xs:element>
							<xs:element name="name" type="xs:string"></xs:element>
							<xs:element name="location" type="xs:string"></xs:element>
							<xs:element name="salary" type="xs:float"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== shankar-trainer/hello-world/tibco-webservice-batch/xml/XmlProject/EmployeeDetails1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:EmployeeDetails xmlns:tns="http://www.example.org/EmployeeDetails" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/EmployeeDetails EmployeeDetails.xsd ">
  <tns:employee>
    <tns:id>10001</tns:id>
    <tns:name>amitendra</tns:name>
    <tns:location>chennai</tns:location>
    <tns:salary>12000</tns:salary>
  </tns:employee>
  
  <tns:employee>
    <tns:id>10001</tns:id>
    <tns:name>amitendra</tns:name>
    <tns:location>chennai</tns:location>
    <tns:salary>12000</tns:salary>
  </tns:employee>
  
  
  
</tns:EmployeeDetails>
