=== shankar-trainer/hello-world/tibco-webservice-batch/xml/XmlProject/insurance.dtd
<!ELEMENT insurances (insurance)+ >
<!ELEMENT insurance (name,maturity,emi-amount,maturity-amount,(city|location),state,country)>
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (fname,lname)> 
<!ELEMENT fname (#PCDATA)> 
<!ELEMENT lname (#PCDATA)> 
<!ELEMENT maturity (#PCDATA)> 
<!ELEMENT emi-amount (#PCDATA)> 
<!ELEMENT maturity-amount (#PCDATA)> 
<!ELEMENT city (#PCDATA)> 
<!ELEMENT location (#PCDATA)> 
<!ELEMENT state (#PCDATA)> 
<!ELEMENT country (#PCDATA)> 

<!ATTLIST insurance id CDATA #IMPLIED>
<!ENTITY country 'india'>
<!ENTITY state 'tamilnadu'>

=== shankar-trainer/hello-world/tibco-webservice-batch/xml/XmlProject/Insurance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE insurances SYSTEM "insurance.dtd">
<insurances>
	<insurance id='8989'>
		<name>
			<fname>health</fname>
			<lname>insurance</lname>
		</name>
		<maturity>5</maturity>
		<emi-amount>5000</emi-amount>
		<maturity-amount>80</maturity-amount>
		<city>chennai</city>
		<state>&state;
		</state>
		<country>&country;
		</country>
	</insurance>

	<insurance>

		<name>
			<fname>life</fname>
			<lname>life</lname>
		</name>
		<maturity>15</maturity>
		<emi-amount>20000</emi-amount>
		<maturity-amount>500000</maturity-amount>
		<location>sipkot</location>
		<state>&state;</state>
		<country>&country;</country>
	</insurance>
</insurances>
